### ISSUE TITLE
Usage of `/var/db/xbps` from two (or more) different systems is not supported

### ISSUE THREAD

**Issue by Johnnynator** [gch1p/voidnsrun#4]
Reusing the hosts `/var/db/xbps` does break systems, since the `pkgdb` of the host system will just be appended with the packages in the `VOIDNSRUN_DIR` (and vice versa).
Take a look at the output of e.g. `xbps-pkgdb -a`, you should see a ton of packages reported as broken if this is executed inside voidnsrun. 

Using xbps-install inside `voidnsrun`, as suggested in your README, will not do what you want, since the `pkgdb` that was created with the initialization of `/glibc` will not be inside the `namespace`, so the host one will be used and "corrupted".

**Comment by Johnnynator** [comment]
For reference, this caused https://github.com/void-linux/void-packages/issues/32184

**Comment by gch1p** [comment]
Hi. Thanks for reporting this but it's not actually true. When you use `xbps-install` with `voidnsrun`, it [bind-mounts](https://github.com/gch1p/voidnsrun/blob/master/voidnsrun.c#L313) `/var` and `/etc` from the container. The host pkgdb is therefore never used so it can't be corrupted.

The reason why `xbps-pkgdb -a` reports ton of broken packages is that `xbps-pkgdb` was not added to the list of xbps commands [here](https://github.com/gch1p/voidnsrun/blob/master/utils.c#L117), which is, indeed, not good.

Fixed with 7d79c86285de5da04d22827c149c6a46886159ee.

**Comment by stormbeforesunsetbee** [comment]
Thanks for the fix :)
